services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Сервис-обертка отправки писем.
  custom_mail_sender:
    class: Proklung\Notifier\Email\CustomMailer
    arguments:
      - '@mailer'
      - '@Symfony\Bridge\Twig\Mime\BodyRenderer'

  Proklung\Notifier\Email\CustomMailer: '@custom_mail_sender'

  Symfony\Bridge\Twig\Mime\BodyRenderer:
    class: Symfony\Bridge\Twig\Mime\BodyRenderer
    arguments: ['@twig.instance']

  Symfony\Component\Mime\BodyRendererInterface: '@Symfony\Bridge\Twig\Mime\BodyRenderer'
